name: Frontend and Backend CI/CD

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Check out the code with full history to avoid missing files
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          fetch-depth: 0  # Ensures everything is checked out

      # Step 2: List files to debug missing package.json
      - name: List files in the directory
        run: ls -R

      # Step 3: Set up Node.js environment
      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '16'

      # Step 4: Install frontend dependencies
      - name: Install frontend dependencies
        run: |
          cd frontend/business-travel-frontend  # Adjust this path if necessary
          npm install

      # Step 5: Run frontend tests
      - name: Run frontend tests with Vitest
        run: |
          cd frontend/business-travel-frontend  # Adjust this path if necessary
          npm run test:coverage

      # Step 6: Upload frontend coverage report as artifact
      - name: Upload frontend coverage report
        uses: actions/upload-artifact@v3
        with:
          name: frontend-coverage-report
          path: frontend/business-travel-frontend/coverage/

      # Step 7: Install backend dependencies
      - name: Install backend dependencies
        run: |
          cd backend  # Adjust this path if necessary
          npm install

      # Step 8: Run backend tests (if applicable)
      - name: Run backend tests
        run: |
          cd backend  # Adjust this path if necessary
          npm test

      # Step 9: Upload backend coverage report as artifact (if applicable)
      - name: Upload backend coverage report
        uses: actions/upload-artifact@v3
        with:
          name: backend-coverage-report
          path: backend/coverage/  # Adjust this path if necessary
