name: CI/CD Workflow

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  # Frontend Job
  frontend:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Node.js for frontend
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Cache frontend Node.js dependencies
        uses: actions/cache@v3
        with:
          path: frontend/business-travel-frontend/node_modules
          key: ${{ runner.os }}-node-modules-${{ hashFiles('frontend/business-travel-frontend/**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-node-modules-

      - name: Install dependencies for frontend with legacy-peer-deps
        run: |
          cd frontend/business-travel-frontend
          npm install --legacy-peer-deps

      - name: Run frontend unit tests with coverage
        run: |
          cd frontend/business-travel-frontend
          npm run test:coverage

      - name: Upload frontend test coverage reports as artifact
        uses: actions/upload-artifact@v3
        with:
          name: frontend-coverage
          path: frontend/business-travel-frontend/coverage

      - name: Build frontend app
        run: |
          cd frontend/business-travel-frontend
          npm run build

      - name: Save frontend build artifacts
        uses: actions/upload-artifact@v3
        with:
          name: frontend-build
          path: frontend/business-travel-frontend/dist

  # Backend Job
  backend:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Node.js for backend
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Cache backend Node.js dependencies
        uses: actions/cache@v3
        with:
          path: backend/business-travel-backend/node_modules
          key: ${{ runner.os }}-node-modules-${{ hashFiles('backend/business-travel-backend/**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-node-modules-

      - name: Install dependencies for backend
        run: |
          cd backend/business-travel-backend
          npm install

      - name: Run backend unit tests with coverage
        run: |
          cd backend/business-travel-backend
          npm run test:coverage

      - name: Upload backend test coverage reports as artifact
        uses: actions/upload-artifact@v3
        with:
          name: backend-coverage
          path: backend/business-travel-backend/coverage

  # Docker Build and Push Job
  docker:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build Docker image
        run: |
          docker build -t ${{ secrets.DOCKER_USERNAME }}/business-travel-backend:latest ./backend/business-travel-backend

      - name: Push Docker image
        run: |
          docker push ${{ secrets.DOCKER_USERNAME }}/business-travel-backend:latest

  # Deployment Job
  deploy:
    runs-on: ubuntu-latest
    needs: [frontend, backend, docker]
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: List files in the root directory for debugging
        run: |
          ls -R .

      - name: List files in the frontend directory for debugging
        run: |
          ls -R ./frontend

      - name: Change to frontend directory and deploy
        run: |
          cd frontend/business-travel-frontend
          npm install -g vercel
          vercel deploy --prod --token ${{ secrets.VERCEL_TOKEN }} --yes
